### ISSUE TITLE
missing htdocs/admin/postfixadmin/ ?

### ISSUE THREAD

**Issue by ta1yanagiya** [designet-inc-oss/postLDAPadmin#1]
The "htdocs/admin/postfixadmin/" directory does not exist in postLDAPadmin-4.0.0.

When I log in from the administrator interface, it will be redirected to the URL below and become "Not Found".

  [POST] http://(server_name)/postldapadmin/admin/index.php (Log in:OK)
    ↓
  [POST] http://(server_name)/postldapadmin/admin/postldapadmin/user/index.php (Not Found)

**Comment by designet-inc-oss** [comment]
Have you followed this manual for setup?

https://www.designet.co.jp/open_source/postldapadmin/

**Comment by ta1yanagiya** [comment]
Yes, I did that.

I extracted the postLDAPadmin-4.0.0.zip file (1 file, not 4 tar.gz-files).

**Comment by designet-inc-oss** [comment]
In our manual, the procedure is to download each of the four tar.gz files and then extract them.

As noted in the manual, the contents of each tar.gz must be placed in a specific location.

https://www.designet.co.jp/open_source/postldapadmin/node4.php#id2
```
# tar zxf postLDAPadmin_frame-VERSION.tar.gz -C /usr/local
# tar zxf postLDAPadmin_admin-VERSION.tar.gz -C /usr/local/postldapadmin/htdocs/admin
# tar zxf postLDAPadmin_user-VERSION.tar.gz -C /usr/local/postldapadmin/htdocs
# tar zxf postLDAPadmin_lib-VERSION.tar.gz -C /usr/local/postldapadmin/lib
```

When extracted from zip, the contents of the four tar.gz files have been combined into a single directory.
Therefore, the directory structure is likely to be different.
Please use the same directory structure as in the table on the following page.

https://www.designet.co.jp/open_source/postldapadmin/node4.php#id24

**Comment by ta1yanagiya** [comment]
> https://www.designet.co.jp/open_source/postldapadmin/node4.php#id24

First "/usr/local/postldapadmin/htdocs/admin/postldapadmin" directory does not exist in postLDAPadmin-4.0.0.zip.
Which directory within postLDAPadmin-4.0.0.zip corresponds to that?

**Comment by designet-inc-oss** [comment]
If extracted from a zip,
```/usr/local/postldapadmin/htdocs/admin/postldapadmin```  directory must be created.
Once created, the following directories and files to Move them under ```/usr/local/postldapadmin/htdocs/admin/postldapadmin```.
- adminpass
- initial
- ml
- user

**Comment by ta1yanagiya** [comment]
Oh, I can log in !!
Thank you.
